[build]
  publish = "."
  command = "echo 'No build needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyD6LjxYTrK8HaBOdCb3zMdqs2PQ3v37fVM"
  VITE_FIREBASE_AUTH_DOMAIN = "sampatrouille-2ad1a.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "sampatrouille-2ad1a"
  VITE_FIREBASE_STORAGE_BUCKET = "sampatrouille-2ad1a.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "350840821095"
  VITE_FIREBASE_APP_ID = "1:350840821095:web:3dc8ef94ddde2d6329cbc2"
